##MERN -> MongoDB[v]; Express.js; React; Node.js

services:
  mongodb: 
    image: mongo:8.2.1
    ports:
      -27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: supersecret123!

  nodeapp:
    build: ./backend
    ports:
      -5000:5000